### Import Library

In [1]:
import numpy as np

#### Math Operations

In [2]:
a = np.array([[1,2],[3,4]])

In [3]:
a

array([[1, 2],
       [3, 4]])

In [4]:
b = np.array([[5,6], [7,8]])

In [5]:
b

array([[5, 6],
       [7, 8]])

In [6]:
np.add(a,b)

array([[ 6,  8],
       [10, 12]])

In [7]:
np.multiply(a,b)

array([[ 5, 12],
       [21, 32]])

In [8]:
np.ndim(a) # dimension of a

2

In [9]:
np.shape(a)

(2, 2)

In [10]:
np.size(a) # how manyelements in list a

4

In [11]:
a.reshape((1,4))

array([[1, 2, 3, 4]])

In [12]:
x = np.arange(16).reshape(2,8)
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [13]:
y = np.arange(1,32,2).reshape(2,8)
y

array([[ 1,  3,  5,  7,  9, 11, 13, 15],
       [17, 19, 21, 23, 25, 27, 29, 31]])

In [14]:
x/y

array([[0.        , 0.33333333, 0.4       , 0.42857143, 0.44444444,
        0.45454545, 0.46153846, 0.46666667],
       [0.47058824, 0.47368421, 0.47619048, 0.47826087, 0.48      ,
        0.48148148, 0.48275862, 0.48387097]])

In [15]:
x = np.arange(31)
np.sin(x)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111, -0.99999021, -0.53657292,  0.42016704,  0.99060736,
        0.65028784, -0.28790332, -0.96139749, -0.75098725,  0.14987721,
        0.91294525,  0.83665564, -0.00885131, -0.8462204 , -0.90557836,
       -0.13235175,  0.76255845,  0.95637593,  0.27090579, -0.66363388,
       -0.98803162])

In [16]:
np.cos(x)

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362,
        0.28366219,  0.96017029,  0.75390225, -0.14550003, -0.91113026,
       -0.83907153,  0.0044257 ,  0.84385396,  0.90744678,  0.13673722,
       -0.75968791, -0.95765948, -0.27516334,  0.66031671,  0.98870462,
        0.40808206, -0.54772926, -0.99996083, -0.53283302,  0.42417901,
        0.99120281,  0.64691932, -0.29213881, -0.96260587, -0.74805753,
        0.15425145])

In [17]:
np.tan(x)

array([ 0.00000000e+00,  1.55740772e+00, -2.18503986e+00, -1.42546543e-01,
        1.15782128e+00, -3.38051501e+00, -2.91006191e-01,  8.71447983e-01,
       -6.79971146e+00, -4.52315659e-01,  6.48360827e-01, -2.25950846e+02,
       -6.35859929e-01,  4.63021133e-01,  7.24460662e+00, -8.55993401e-01,
        3.00632242e-01,  3.49391565e+00, -1.13731371e+00,  1.51589471e-01,
        2.23716094e+00, -1.52749853e+00,  8.85165604e-03,  1.58815308e+00,
       -2.13489670e+00, -1.33526407e-01,  1.17875355e+00, -3.27370380e+00,
       -2.81429605e-01,  8.87142844e-01, -6.40533120e+00])