## Import Library

In [1]:
import torch # for pytorch
import torchvision # for pytorch
import numpy as np # for numpy

### Create numpy& torch data

In [2]:
np_data = np.arange(6).reshape((2,3))

torch_data = torch.from_numpy(np_data) # convert numpy data to tensor
tensor2array = torch_data.numpy() # convert torch data to numpy data

In [3]:
np_data

array([[0, 1, 2],
       [3, 4, 5]])

In [4]:
torch_data # torch data must be a tensor(張量)

tensor([[0, 1, 2],
        [3, 4, 5]], dtype=torch.int32)

In [5]:
tensor2array

array([[0, 1, 2],
       [3, 4, 5]])

In [6]:
np_data2 = np.array([1,0,-1,-2])
# abs
torch_data2 = torch.abs(torch.FloatTensor(np_data2)) # torch 在做科學計算時候必須得轉為tensor才可運算
torch_data2

tensor([1., 0., 1., 2.])

#### torch 操作跟 numpy 類似(只是numpy是矩陣運算，torch是tensor運算)

In [7]:
torch_data2 = torch.IntTensor(np_data2) # convert to tensor
torch_data2

tensor([ 1,  0, -1, -2], dtype=torch.int32)

In [8]:
torch_data2 = torch.DoubleTensor(np_data2) # convert to tensor
torch_data2

tensor([ 1.,  0., -1., -2.], dtype=torch.float64)

In [9]:
torch_data2 = torch.FloatTensor(np_data2) # convert to tensor(32-bits floating point
torch_data2

tensor([ 1.,  0., -1., -2.])

#### Math Operations

In [10]:
print('numpy sin\n',np.sin(np_data2),
     '\nnumpy mean(平均數)\n', np.mean(np_data2))

numpy sin
 [ 0.84147098  0.         -0.84147098 -0.90929743] 
numpy mean(平均數)
 -0.5


In [11]:
print('torch sin\n',torch.sin(torch_data2),
     '\ntorch mean(平均數)\n', torch.mean(torch_data2))

torch sin
 tensor([ 0.8415,  0.0000, -0.8415, -0.9093]) 
torch mean(平均數)
 tensor(-0.5000)


In [15]:
data = [[1,2], [3,4]]
tensor = torch.FloatTensor(data)
print('numpy matrix multipy\n', np.matmul(data,data),
     '\ntorch matrix multipy\n', tensor.mm(tensor,tensor)) # mm == matmul

numpy matrix multipy
 [[ 7 10]
 [15 22]] 
torch matrix multipy
 tensor([[ 7., 10.],
        [15., 22.]])
