## Import Library

In [1]:
import torch
from torch.autograd import Variable

In [2]:
tensor = torch.FloatTensor([[1,2], [3,4]])
variable = Variable(tensor, requires_grad=True) # requires_grad 是否要涉及到反向傳播, 預設為False

反向傳播意思是在 autograd模組中實現了計算圖的相關功能，autograd 中的核心資料結構是 Variable。我們可以認為需要求導 (requires_grad) 的 tensor 即 Variable. autograd記錄對 tensor 的操作記錄用來構建計算圖。

In [3]:
print(tensor)

tensor([[1., 2.],
        [3., 4.]])


In [4]:
print(variable)

tensor([[1., 2.],
        [3., 4.]], requires_grad=True)


In [5]:
t_out = torch.mean(tensor*tensor) # == torch^2
v_out = torch.mean(variable*variable)

In [6]:
t_out

tensor(7.5000)

In [7]:
v_out

tensor(7.5000, grad_fn=<MeanBackward0>)

In [8]:
v_out.backward() # t_out.backward() # tensor 不能反向傳遞

v_out = 1 / (sum_of_elements) * sum(var*var)
梯度 = d(v_out) / d(var) = 1 / (sum_of_elements) * 2 * variable

In [9]:
variable.grad

tensor([[0.5000, 1.0000],
        [1.5000, 2.0000]])

In [10]:
variable # variable 型態

tensor([[1., 2.],
        [3., 4.]], requires_grad=True)

In [11]:
variable.data #轉為 tensor 型態

tensor([[1., 2.],
        [3., 4.]])

In [12]:
variable.data.numpy() #轉為 numpy 型態

array([[1., 2.],
       [3., 4.]], dtype=float32)