### Import Library

In [1]:
import tensorflow as tf
import keras
import numpy as np
import matplotlib.pyplot as plt

D:\anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
D:\anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
D:\anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
D:\anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:519: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is 

#### 0D 張量，也就是純量值(Scalar)，dtype = float32, float64

In [2]:
x = np.array(10.5)
print(x)
print(x.ndim)

10.5
0


#### ------------------------------------------------- new line -------------------------------------------------

#### 1D 張量，也就是向量(vector)

In [3]:
x = np.array([1.2,2.4,3.6,4.8,6.0])
print(x)
print(x.ndim)

[1.2 2.4 3.6 4.8 6. ]
1


#### ------------------------------------------------- new line -------------------------------------------------

#### 2D 張量，也就是矩陣(Matrix)

In [4]:
x = np.array([[i for i in range(6)],
              [i for i in range(6)],
              [i for i in range(6)]])
print(x)
print(x.ndim)
print(x.shape) # shape = H*W

[[0 1 2 3 4 5]
 [0 1 2 3 4 5]
 [0 1 2 3 4 5]]
2
(3, 6)


#### ------------------------------------------------- new line -------------------------------------------------

#### 3D 張量，也就是三維陣列 (樣本數, 時間間距, 特徵值) Ex. 1000天資訊，每天有240分鐘，每分鐘有三種可能性 (1000,240,3)

In [5]:
x = np.array([[i for i in range(6)],
              
              [i for i in range(6)],
              
              [i for i in range(6)]])
print(x)
print(x.ndim)
print(x.shape)

[[0 1 2 3 4 5]
 [0 1 2 3 4 5]
 [0 1 2 3 4 5]]
2
(3, 6)


#### ------------------------------------------------- new line -------------------------------------------------

#### 4D 張量，(樣本數, 寬度, 高度, 色彩數)
#### ------------------------------------------------- new line -------------------------------------------------
#### 5D 張量，(樣本數, 畫面數, 寬度, 高度, 色彩數)

#### ------------------------------------------------- new line -------------------------------------------------