## Import Library

In [1]:
import torch
import numpy as np

numpy 和 torch 使用方式很相似。
只是numpy 的dtype 是ndarray；
而我是torch 是tensor

### Create a tensor

In [2]:
x = torch.empty(1)
x
# Returns a tensor filled with uninitialized data.
# The shape of the tensor is defined by the variable argument size

tensor([8.9082e-39])

In [3]:
y = torch.zeros(1)
y
# Returns a tensor filled with the scalar value 0,
# with the shape defined by the variable argument size.

tensor([0.])

### Data type

In [4]:
x.dtype

torch.float32

### torch from list

In [5]:
x2 = torch.tensor([2.5, -0.1])
x2

tensor([ 2.5000, -0.1000])

### Operations

In [6]:
x3 = torch.rand(2,2)
y3 = torch.rand(2,2)
print('x3\n',x3,
     '\ny3\n', y3)

x3
 tensor([[0.7818, 0.5584],
        [0.8630, 0.9772]]) 
y3
 tensor([[0.2927, 0.1122],
        [0.5552, 0.3159]])


In [7]:
add_z = torch.add(x3,y3) # == x3 + y3
add_z

tensor([[1.0746, 0.6706],
        [1.4181, 1.2931]])

In [8]:
sub_z = torch.sub(x3,y3) # == x3 - y3
sub_z

tensor([[0.4891, 0.4462],
        [0.3078, 0.6613]])

In [9]:
mul_z = torch.mul(x3,y3) # == x3 * y3
mul_z

tensor([[0.2289, 0.0626],
        [0.4791, 0.3087]])

In [10]:
div_z = torch.div(x3,y3) # == x3 / y3
div_z

tensor([[2.6707, 4.9770],
        [1.5544, 3.0936]])

In [11]:
x = torch.rand(5,5)
x

tensor([[0.2741, 0.3779, 0.8005, 0.5480, 0.3365],
        [0.8801, 0.4028, 0.0512, 0.7775, 0.4907],
        [0.1314, 0.1235, 0.8460, 0.8464, 0.8909],
        [0.1201, 0.6823, 0.4264, 0.4293, 0.3648],
        [0.0749, 0.3725, 0.2421, 0.3039, 0.7881]])

In [12]:
x[1,:2]

tensor([0.8801, 0.4028])

In [13]:
x[1,1].item() # only one element tensors can be converted to Python scalars

0.4027627110481262

### Reshape a tensor

In [14]:
x = torch.rand(4, 4)
y = x.view(16) # == np.reshape == tensor_value.reshape(16)
y

tensor([0.5024, 0.6866, 0.5881, 0.9476, 0.9562, 0.2516, 0.2598, 0.9092, 0.8217,
        0.3411, 0.9508, 0.1529, 0.8254, 0.7732, 0.3678, 0.1039])

## numpy vs torch

In [15]:
a = torch.ones(5)
a

tensor([1., 1., 1., 1., 1.])

In [16]:
b = a.numpy() # convert tensor 'a' into numpy 'b'.
b

array([1., 1., 1., 1., 1.], dtype=float32)

In [18]:
a.add(a)

tensor([2., 2., 2., 2., 2.])

In [21]:
b # if share the same CPU or GPU, the value will as same as variable a

array([1., 1., 1., 1., 1.], dtype=float32)

In [22]:
c = torch.from_numpy(b) # convert numpy 'b' into tensor 'c'.
c

tensor([1., 1., 1., 1., 1.])

## Check install CUDA toolkit

In [28]:
if torch.cuda.is_available():
    device = torch.device("cuda")
    x = torch.ones(5, device=device) # create tensor on the GPU
    y = torch.ones(5)
    y = y.to(device) # let tensor y run on GPU CUDA toolkit
    z = x + y

 記得一件事，numpy 只能運行在 CPU上，而 pytorch可以在 CPU或是 GPU